trigger:
  branches:
    include:
      - main  # Trigger when pushing to the main branch

stages:
stages:
- stage: PrismaScan
  displayName: "Prisma Scan"
  jobs:
  - job: FetchScanResults
    displayName: "Fetch Prisma Scan Results from GitHub"
    pool:
      name: "Default"  # Replace with your actual agent pool
    steps:
    - script: |
        echo "Fetching Prisma Cloud scan results from GitHub Actions..."
        RUN_ID=$(curl -s -H "Authorization: Bearer $(GITHUB_PAT)" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/fir36/prisma_scan/actions/runs \
            | jq -r '.workflow_runs[0].id')

        echo "GitHub Action Run ID: $RUN_ID"

        echo "Fetching logs..."
        curl -s -H "Authorization: Bearer $(GITHUB_PAT)" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/fir36/prisma_scan/actions/runs/$RUN_ID/logs \
            > github_scan_logs.zip

        echo "Download complete. Extracting logs..."
        unzip -o github_scan_logs.zip -d github_logs/
        
        echo "Displaying scan logs..."
        cat github_logs/*
      env:
        GITHUB_PAT: $(GITHUB_PAT)

- stage: Development
  displayName: "Development Stage"
  dependsOn: PrismaScan
  jobs:
  - job: Build
    displayName: "Build the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Building the application..."

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Development
  jobs:
  - job: Deploy
    displayName: "Deploy the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Deploying the application..."
