trigger:
  branches:
    include:
      - main  # Trigger when pushing to the main branch

stages:
- stage: PrismaScan
  displayName: "Prisma Scan"
  jobs:
  - job: FetchScanResults
    displayName: "Fetch Prisma Scan Results from GitHub"
    pool:
      name: "Default"  # Replace with your actual agent pool
    steps:
    - script: |
        echo "Fetching Prisma Cloud scan results from GitHub Actions..."

            # Fetch latest GitHub Action Run ID
        RESPONSE=$(curl -s -H "Authorization: Bearer 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" \
        -H "Accept: application/vnd.github.v3+json" \
        "https://api.github.com/fir36/prisma_scan/actions/runs")

        echo "GitHub API Response:"
        echo "$RESPONSE"  # Print full response for debugging
    
        # Fetch latest GitHub Action Run ID
        RUN_ID=$(curl -s -H "Authorization: Bearer $GITHUB_PAT" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/fir36/prisma_scan/actions/runs \
            | jq -r '.workflow_runs[0].id')

        if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
          echo "❌ Failed to get GitHub Action Run ID"
          exit 1
        fi

        echo "✅ GitHub Action Run ID: $RUN_ID"

        # Fetch logs
        echo "Fetching logs..."
        curl -s -H "Authorization: Bearer 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" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/fir36/prisma_scan/actions/runs/$RUN_ID/logs \
            -o github_scan_logs.zip

        if [ ! -f "github_scan_logs.zip" ]; then
          echo "❌ Log download failed!"
          exit 1
        fi

        echo "✅ Download complete. Extracting logs..."
        sudo apt-get update && sudo apt-get install -y unzip
        unzip -o github_scan_logs.zip -d github_logs/
        
        echo "✅ Displaying scan logs..."
        cat github_logs/*
      env:
        GITHUB_PAT: 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

- stage: Development
  displayName: "Development Stage"
  dependsOn: PrismaScan
  jobs:
  - job: Build
    displayName: "Build the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Building the application..."

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Development
  jobs:
  - job: Deploy
    displayName: "Deploy the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Deploying the application..."
