trigger:
  branches:
    include:
      - main  # Trigger when pushing to the main branch

stages:
- stage: PrismaScan
  displayName: "Prisma Scan"
  jobs:
  - job: RunGithubAction
    displayName: "Trigger GitHub Action for Prisma Scan"
    pool:
      name: "Default"  # Replace with your actual agent pool name
    steps:
    - script: |
        echo "Triggering GitHub Action for Prisma Scan..."
      #   curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
      #        -H "Authorization: token $(GITHUB_PAT)" \
      #        https://api.github.com/repos/<your-org>/<your-repo>/actions/workflows/<your-github-action.yml>/dispatches \
      #        -d '{"ref":"main"}'
      # env:
      #   GITHUB_PAT: $(GITHUB_PAT) # GitHub Personal Access Token (store in Azure DevOps secrets)

- stage: Development
  displayName: "Development Stage"
  dependsOn: PrismaScan
  jobs:
  - job: Build
    displayName: "Build the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Building the application..."

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Development
  jobs:
  - job: Deploy
    displayName: "Deploy the Application"
    pool:
      name: "Default"  # Use the same agent pool
    steps:
    - script: echo "Deploying the application..."
