trigger:
  branches:
    include:
      - main  # Runs on push to the main branch

stages:
  - stage: PrismaCloudScan
    displayName: "Prisma Cloud Security Scan"
    jobs:
      - job: PrismaScan
        displayName: "Run Prisma Cloud Security Scan"
        pool:
          vmImage: default  # Uses the latest Ubuntu runner
        steps:
          - checkout: self  # Checks out the repository code

          - task: Bash@3
            displayName: "Run Prisma Cloud Checkov Scan"
            env:
              PRISMA_API_URL: "https://api.sg.prismacloud.io"  # Prisma Cloud API URL
              BC_API_KEY: $(BC_API_KEY)  # API key stored in Azure DevOps secrets
            script: |
              pip install checkov
              checkov -d . --bc-api-key $BC_API_KEY

  - stage: Development
    displayName: "Deploy to Development"
    dependsOn: PrismaCloudScan  # Runs only if Prisma scan succeeds
    condition: succeeded()
    jobs:
      - job: DeployDev
        displayName: "Deploy to Dev Environment"
        pool:
          vmImage: default
        steps:
          - script: echo "Deploying to Development"
          - script: echo "Running unit tests"

  - stage: UAT
    displayName: "Deploy to UAT"
    dependsOn: Development  # Ensures Development runs first
    condition: succeeded()
    jobs:
      - job: DeployUAT
        displayName: "Deploy to UAT Environment"
        pool:
          vmImage: default
        steps:
          - script: echo "Deploying to UAT"
          - script: echo "Running integration tests"

  - stage: Production
    displayName: "Deploy to Production"
    dependsOn: UAT  # Ensures UAT runs first
    condition: succeeded()
    jobs:
      - job: DeployProd
        displayName: "Deploy to Production"
        pool:
          vmImage: default
        steps:
          - script: echo "Deploying to Production"
          - script: echo "Running final verification tests"
