trigger:
  branches:
    include:
      - main  # Runs on push to the main branch

stages:
  - stage: PrismaCloudScan
    displayName: "Prisma Cloud Security Scan"
    jobs:
      prisma-cloud-scan:
        runs-on: ubuntu-latest  # Uses the latest Ubuntu runner

        steps:
        - name: Checkout repo
          uses: actions/checkout@v2  # Checks out the repository code

        - name: Run Prisma Cloud
          id: prisma-cloud
          uses: bridgecrewio/checkov-action@master  # Uses the Checkov action to scan your code
          env:
            PRISMA_API_URL: https://api.sg.prismacloud.io  # Prisma Cloud API URL
          with:
            api-key: ${{ secrets.BC_API_KEY }}

  - stage: Development
    displayName: "Deploy to Development"
    dependsOn: PrismaCloudScan  # Runs only if Prisma scan succeeds
    condition: succeeded()
    jobs:
      - job: DeployDev
        displayName: "Deploy to Dev Environment"
        steps:
          - script: echo "Deploying to Development"
          - script: echo "Running unit tests"

  - stage: UAT
    displayName: "Deploy to UAT"
    dependsOn: Development  # Ensures Development runs first
    condition: succeeded()
    jobs:
      - job: DeployUAT
        displayName: "Deploy to UAT Environment"
        steps:
          - script: echo "Deploying to UAT"
          - script: echo "Running integration tests"

  - stage: Production
    displayName: "Deploy to Production"
    dependsOn: UAT  # Ensures UAT runs first
    condition: succeeded()
    jobs:
      - job: DeployProd
        displayName: "Deploy to Production"
        steps:
          - script: echo "Deploying to Production"
          - script: echo "Running final verification tests"
