trigger:
  branches:
    include:
      - main  # Trigger pipeline when GitHub pushes to main

stages:
  - stage: Scan
    displayName: "Prisma Cloud Security Scan"
    jobs:
      - job: PrismaScan
        pool:
          name: Default  # Uses self-hosted runner (same as GitHub Actions)
        steps:
          - script: |
              echo "Checking if Prisma Cloud scan results exist..."
              if [ -f /shared-folder/prisma-scan-result.txt ]; then
                echo "Prisma Cloud Scan Completed"
              else
                echo "Scan results not found! Exiting..."
                exit 1
              fi
          - script: cat /shared-folder/prisma-scan-result.txt

  - stage: Development
    displayName: "Deploy to Development"
    dependsOn: Scan  # Runs only if the scan succeeds
    condition: succeeded()
    jobs:
      - job: DeployDev
        pool:
          name: Default
        steps:
          - script: echo "Deploying to Development..."
          - script: echo "Running unit tests"

  - stage: Deployment
    displayName: "Deploy to Production"
    dependsOn: Development  # Runs only if development succeeds
    condition: succeeded()
    jobs:
      - job: DeployProd
        pool:
          name: Default
        steps:
          - script: echo "Deploying to Production..."
          - script: echo "Running final verification tests"
