trigger:
  branches:
    include:
      - main  # Runs only when pushing to main

pr: none  # Prevents PR-triggered runs

stages:
  - stage: Prisma_Scan
    displayName: "GitHub Security Scan"
    jobs:
      - job: wait_for_github_scan
        displayName: "Wait for GitHub Scan to Complete"
        pool: server  # Runs without an agent
        steps:
          - checkout: none  # No need to checkout code

          - script: |
              echo "Waiting for GitHub Action to complete..."
              sleep 60  # Optional delay to allow the scan to complete

  - stage: Development
    displayName: "Development"
    dependsOn: Prisma_Scan  # Runs after GitHub scan
    jobs:
      - job: build_and_test
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v2

          - name: Build and Test
            run: echo "Building and testing application"

  - stage: Deploy
    displayName: "Deploy"
    dependsOn: Development  # Runs after Development
    jobs:
      - job: deploy_app
        runs-on: ubuntu-latest
        steps:
          - name: Deploy Application
            run: echo "Deploying application"
